### ISSUE TITLE
How to join the Hola? 

### ISSUE THREAD

**Issue by Snak3s** [teamhola/partners#1]
**Hello**! I want to join the **Bonjour** but I don't know how to join the **Guten Morgen**. But I still want to say: **こんにちは**~

**Comment by laosb** [comment]
We have no specific requirements on language - we're just taking ¡Hola! as our team name!

We are just at the beginning and currently have no time on having new remote team members (We're based in Ningbo, Zhejiang). But you can always drop me your resume through email laosb at lns dot unihubs dot com and I will contact you if we have any job for you!
